// Danh sách tỉnh thành và quận huyện Việt Nam
export const PROVINCES = [
  "An Giang",
  "Bà Rịa - Vũng Tàu",
  "Bạc Liêu",
  "Bắc Giang",
  "Bắc Kạn",
  "Bắc Ninh",
  "Bến Tre",
  "Bình Định",
  "Bình Dương",
  "Bình Phước",
  "Bình Thuận",
  "Cà Mau",
  "Cần Thơ",
  "Cao Bằng",
  "Đà Nẵng",
  "Đắk Lắk",
  "Đắk Nông",
  "Điện Biên",
  "Đồng Nai",
  "Đồng Tháp",
  "Gia Lai",
  "Hà Giang",
  "Hà Nam",
  "Hà Nội",
  "Hà Tĩnh",
  "Hải Dương",
  "Hải Phòng",
  "Hậu Giang",
  "Hòa Bình",
  "Hưng Yên",
  "Khánh Hòa",
  "Kiên Giang",
  "Kon Tum",
  "Lai Châu",
  "Lâm Đồng",
  "Lạng Sơn",
  "Lào Cai",
  "Long An",
  "Nam Định",
  "Nghệ An",
  "Ninh Bình",
  "Ninh Thuận",
  "Phú Thọ",
  "Phú Yên",
  "Quảng Bình",
  "Quảng Nam",
  "Quảng Ngãi",
  "Quảng Ninh",
  "Quảng Trị",
  "Sóc Trăng",
  "Sơn La",
  "Tây Ninh",
  "Thái Bình",
  "Thái Nguyên",
  "Thanh Hóa",
  "Thừa Thiên Huế",
  "Tiền Giang",
  "TP. Hồ Chí Minh",
  "Trà Vinh",
  "Tuyên Quang",
  "Vĩnh Long",
  "Vĩnh Phúc",
  "Yên Bái",
]

export const STATION_TYPES = [
  "Loại 1",
  "Loại 2",
  "Loại 3",
  "Loại 4",
  "Loại 5",
  "Loại 6",
]

// Mapping tỉnh thành với quận huyện (một số tỉnh phổ biến)
export const DISTRICTS_BY_PROVINCE: Record<string, string[]> = {
  "TP. Hồ Chí Minh": [
    "Q. 1",
    "Q. 2",
    "Q. 3",
    "Q. 4",
    "Q. 5",
    "Q. 6",
    "Q. 7",
    "Q. 8",
    "Q. 9",
    "Q. 10",
    "Q. 11",
    "Q. 12",
    "Q. Bình Thạnh",
    "Q. Bình Tân",
    "Q. Gò Vấp",
    "Q. Phú Nhuận",
    "Q. Tân Bình",
    "Q. Tân Phú",
    "Q. Thủ Đức",
    "H. Bình Chánh",
    "H. Cần Giờ",
    "H. Củ Chi",
    "H. Hóc Môn",
    "H. Nhà Bè",
  ],
  "Hà Nội": [
    "Q. Ba Đình",
    "Q. Hoàn Kiếm",
    "Q. Tây Hồ",
    "Q. Long Biên",
    "Q. Cầu Giấy",
    "Q. Đống Đa",
    "Q. Hai Bà Trưng",
    "Q. Hoàng Mai",
    "Q. Thanh Xuân",
    "H. Sóc Sơn",
    "H. Đông Anh",
    "H. Gia Lâm",
    "H. Nam Từ Liêm",
    "H. Bắc Từ Liêm",
    "H. Mê Linh",
    "H. Hà Đông",
    "H. Sơn Tây",
    "H. Ba Vì",
    "H. Phúc Thọ",
    "H. Đan Phượng",
    "H. Hoài Đức",
    "H. Quốc Oai",
    "H. Thạch Thất",
    "H. Chương Mỹ",
    "H. Thanh Oai",
    "H. Thường Tín",
    "H. Phú Xuyên",
    "H. Ứng Hòa",
    "H. Mỹ Đức",
  ],
  "Đà Nẵng": [
    "Q. Hải Châu",
    "Q. Thanh Khê",
    "Q. Sơn Trà",
    "Q. Ngũ Hành Sơn",
    "Q. Liên Chiểu",
    "Q. Cẩm Lệ",
    "H. Hòa Vang",
    "H. Hoàng Sa",
  ],
  "Cần Thơ": [
    "Q. Ninh Kiều",
    "Q. Ô Môn",
    "Q. Bình Thủy",
    "Q. Cái Răng",
    "Q. Thốt Nốt",
    "H. Vĩnh Thạnh",
    "H. Cờ Đỏ",
    "H. Phong Điền",
    "H. Thới Lai",
  ],
  "Lâm Đồng": [
    "TP. Đà Lạt",
    "TP. Bảo Lộc",
    "H. Đức Trọng",
    "H. Lạc Dương",
    "H. Đơn Dương",
    "H. Đạ Huoai",
    "H. Đạ Tẻh",
    "H. Cát Tiên",
    "H. Đam Rông",
    "H. Lâm Hà",
    "H. Bảo Lâm",
  ],
  "Bà Rịa - Vũng Tàu": [
    "TP. Vũng Tàu",
    "TP. Bà Rịa",
    "H. Châu Đức",
    "H. Xuyên Mộc",
    "H. Long Điền",
    "H. Đất Đỏ",
    "H. Tân Thành",
    "H. Côn Đảo",
  ],
}

// Hàm lấy danh sách quận huyện theo tỉnh thành
export function getDistrictsByProvince(province: string): string[] {
  return DISTRICTS_BY_PROVINCE[province] || []
}

